repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^API\.md$
    -   id: end-of-file-fixer
        exclude: ^API\.md$

-   repo: https://github.com/igrr/astyle_py.git
    rev: v1.1.0
    hooks:
    -   id: astyle_py
        args: ['--style=otbs', '--attach-namespaces', '--attach-classes', '--indent=spaces=4', '--convert-tabs', '--align-pointer=name', '--align-reference=name', '--keep-one-line-statements', '--pad-header', '--pad-oper']
        exclude: ^(imgui/|softraster/|test_apps/.*/managed_components/|test_apps/.*/build/)

-   repo: https://github.com/igrr/code_snippet_to_doc.git
    rev: v0.1.0
    hooks:
    -   id: code_snippet_to_doc
        args: ['--input=README.md']

-   repo: https://github.com/espressif/doxybook
    rev: v0.1.0
    hooks:
    -   id: doxygen-api-md
        args: ["-i", "doxygen/xml", "-o", "./API.md"]
